### CHANGING THIS NUMBER WILL RESET YOUR CONFIG ###
configversion: 2
####
#
# How much should a backpack cost?
# Note: This feature requires Vault: http://dev.bukkit.org/bukkit-plugins/vault/
# Set to 0 to disable
cost: 500

# Update checking.
# Set to false to disable checking for newer versions of the plugin
checkupdate: true

# Data storage.
# flatfile = backpacks will be saved in individual files
# MYSQL = backpacks will be stored in the specified SQL database.
data: flatfile

# MYSQL settings (these will only be used if data saving is set to MYSQL)
mysql:
  database: minecraft
  host: localhost:3306
  user: root
  pass: 12345
  table: Backpacks