name: Backpack
version: 1.0
author: michaelkrauty
main: me.michaelkrauty.Backpack.Main
commands:
  backpack:
    description: the backpack command
    usage: /backpack <give|rename> [name]
permissions:
  backpack.use:
    description: Gives access to /backpack